# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: true
  view:
    formats: { json: true, xml: true, rss: false }
    view_response_listener: true
  format_listener:
    rules:
      - { path: ^/, prefer_extension: true, fallback_format: xml, priorities: [ json ] }
