framework:
  messenger:
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          delay: 500
    routing:
      'App\Message\OrderAutoRejectMessage': async
      'App\Message\OrderApprovedMessage': async
